In [3]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#Carga de un archivo csv
df= pd.read_csv('Actividad 1 Entendimiento de los Datos.csv')
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Identificar valores nulos por columna
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                3
host_total_listings_count          3
host_has_profile_pic               3
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy          5001
review_scores_cleanliness       5000
review_scores_communication     4999
review_scores_location          5001
dtype: int64

In [6]:
#Identificar valores nulos por dataframe
valores_nulos=df.isnull().sum().sum()
valores_nulos

np.int64(58701)

In [7]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(20)

review_scores_location         26.422571
review_scores_accuracy         26.422571
review_scores_cleanliness      26.417287
review_scores_communication    26.412004
review_scores_rating           26.406721
reviews_per_month              26.406721
host_location                  23.120410
beds                           21.413853
price                          21.207798
bathrooms                      21.054578
host_response_time             15.269192
host_response_rate             15.269192
host_acceptance_rate           14.497807
bedrooms                       10.868072
has_availability                5.753685
host_is_superhost               2.995720
bathrooms_text                  0.042268
maximum_minimum_nights          0.021134
minimum_maximum_nights          0.021134
maximum_maximum_nights          0.021134
dtype: float64

In [8]:
#Valores nulos por filas
df[df.isnull().any(axis=1)]

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
7,7,353640,20250612050654,1791076,41.384220,2.184120,"Sant Pere, Santa Caterina i la Ribera",Ciutat Vella,Entire rental unit,Entire home/apt,...,194,2,0,2,1.43,4.56,4.69,4.56,4.88,4.97
10,10,360863,20250612050654,1824328,41.384280,2.195760,la Barceloneta,Ciutat Vella,Private room in rental unit,Private room,...,32,0,0,0,0.20,4.73,4.84,4.84,4.94,4.71
11,11,363601,20250612050654,1837053,41.379610,2.173060,el Raval,Ciutat Vella,Entire rental unit,Entire home/apt,...,25,0,0,0,0.17,4.20,4.26,4.39,4.67,4.54
13,13,36763,20250612050654,158596,41.380430,2.190940,la Barceloneta,Ciutat Vella,Private room in rental unit,Private room,...,108,0,0,0,0.65,4.79,4.88,4.71,4.92,4.92
26,26,71520,20250612050654,366428,41.418410,2.133070,Vallcarca i els Penitents,Gràcia,Entire rental unit,Entire home/apt,...,1,0,0,0,0.01,5.00,4.00,5.00,5.00,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

SUSTITUCIÓN DE VALORES NULOS

In [9]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
df["review_scores_accuracy"]=df["review_scores_accuracy"].fillna(round(df["review_scores_accuracy"].mean(),1))

In [10]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                3
host_total_listings_count          3
host_has_profile_pic               3
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness       5000
review_scores_communication     4999
review_scores_location          5001
dtype: int64


Decidí reemplazar los valores nulos con la media, porque esta variable tiene una distribución relativamente estable y el promedio me ayuda a mantener la tendencia central sin distorsionar los datos.

In [11]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
df["review_scores_cleanliness"]=df["review_scores_cleanliness"].fillna(round(df["review_scores_cleanliness"].median(),1))

In [12]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                3
host_total_listings_count          3
host_has_profile_pic               3
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Aquí usé la mediana, ya que esta medida no se ve afectada por valores atípicos y me permite imputar los nulos de una forma más robusta.

In [13]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df["host_listings_count"] = df["host_listings_count"].fillna(method="ffill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/3325223567.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_listings_count"] = df["host_listings_count"].fillna(method="ffill")

In [14]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          3
host_has_profile_pic               3
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

A esta variable le apliqué forward fill (ffill), porque tiene registros que suelen repetirse y de esa manera aproveché la continuidad de los datos sin inventar valores.

In [15]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df["host_total_listings_count"] = df["host_total_listings_count"].fillna(method="ffill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/1586106239.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_total_listings_count"] = df["host_total_listings_count"].fillna(method="ffill")

In [16]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               3
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

También usé ffill, ya que la lógica es parecida: los valores anteriores me ayudan a rellenar sin perder coherencia en los datos.

In [17]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_has_profile_pic"]=df["host_has_profile_pic"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/3993254451.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_has_profile_pic"]=df["host_has_profile_pic"].fillna(method="bfill")

In [18]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time              2890
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Usé backfill (bfill) porque es una variable categórica con valores repetitivos y rellenar con el valor siguiente me pareció adecuado.

In [19]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_response_time"]=df["host_response_time"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/3285020594.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_response_time"]=df["host_response_time"].fillna(method="bfill")

In [20]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                   4376
host_response_time                 0
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Igual utilicé bfill, ya que el tiempo de respuesta de un host suele ser constante y pude completar los vacíos con valores cercanos.

In [21]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df["host_location"] =df["host_location"].fillna("Barcelona, Spain")

In [22]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                      0
host_response_time                 0
host_response_rate              2890
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Decidí rellenar los nulos con "Barcelona, Spain", porque es la ubicación predominante en la base y me pareció lo más lógico para mantener consistencia.

In [23]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_response_rate"]=df["host_response_rate"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/3964415756.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_response_rate"]=df["host_response_rate"].fillna(method="bfill")

In [24]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate            2744
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Aquí también usé bfill, porque la tasa de respuesta normalmente es estable, y tomar el valor siguiente me permite no dejar huecos.

In [25]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_acceptance_rate"] =df["host_acceptance_rate"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/2539254413.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_acceptance_rate"] =df["host_acceptance_rate"].fillna(method="bfill")

In [26]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         3
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

De nuevo utilicé bfill, ya que la tasa de aceptación también es un valor que no cambia mucho entre registros.

In [27]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_since"]=df["host_since"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/724300966.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_since"]=df["host_since"].fillna(method="bfill")

In [28]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                567
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Apliqué bfill, porque la fecha en la que un host empieza no debería variar mucho y es válido completarla con valores cercanos.

In [29]:
df["host_is_superhost"].value_counts()

host_is_superhost
f    14234
t     4126
Name: count, dtype: int64

In [30]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df["host_is_superhost"]= df["host_is_superhost"].fillna("f") 
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN

In [31]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             3
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

In [32]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df["host_identity_verified"] =df["host_identity_verified"].fillna(method="bfill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/2673152777.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_identity_verified"] =df["host_identity_verified"].fillna(method="bfill")

In [33]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                       3985
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Aquí también usé bfill, ya que la verificación de identidad es un dato binario y estable, así que tiene sentido completarlo con valores vecinos.

In [34]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df["bathrooms"]= df["bathrooms"].fillna(0) 
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN

In [35]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     8
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

En este caso, puse los nulos como 0, ya que si no se especifica, lo más conservador es asumir que no hay baños registrados.

In [36]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df["bathrooms_text"] =df["bathrooms_text"].fillna(method="ffill")

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/2966954759.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["bathrooms_text"] =df["bathrooms_text"].fillna(method="ffill")

In [37]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     0
bedrooms                        2057
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Utilicé ffill, porque este texto suele estar relacionado con la variable anterior y se puede heredar del registro inmediato.

In [38]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df["bedrooms"]= df["bedrooms"].fillna(0) 
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN

In [39]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     0
bedrooms                           0
beds                            4053
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Rellené con 0, porque si no está definido, lo más lógico es que se registraron

In [40]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df["beds"]= df["beds"].fillna(0) 
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,4.70,4.80,NaN,NaN

In [41]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     0
bedrooms                           0
beds                               0
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication     4999
review_scores_location          5001
dtype: int64

Igual que en bedrooms, los nulos los pasé a 0, ya que sin información es mejor asumir el mínimo.

In [42]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
df["review_scores_communication"]=df["review_scores_communication"].fillna(round(df["review_scores_communication"].mean(),1))

In [43]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     0
bedrooms                           0
beds                               0
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication        0
review_scores_location          5001
dtype: int64

In [44]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
df["review_scores_location"]=df["review_scores_location"].fillna(round(df["review_scores_location"].mean(),1))

In [45]:
#Corroboramos valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

Unnamed: 0                         0
id                                 0
scrape_id                          0
host_id                            0
latitude                           0
longitude                          0
neighbourhood_cleansed             0
neighbourhood_group_cleansed       0
property_type                      0
room_type                          0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
accommodates                       0
bathrooms                          0
bathrooms_text                     0
bedrooms                           0
beds                               0
amenities                          0
price                           4014
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights             4
maximum_minimum_nights             4
minimum_maximum_nights             4
maximum_maximum_nights             4
minimum_nights_avg_ntm             0
maximum_nights_avg_ntm             0
has_availability                1089
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
availability_eoy                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
number_of_reviews_ly               0
reviews_per_month               4998
review_scores_rating            4998
review_scores_accuracy             0
review_scores_cleanliness          0
review_scores_communication        0
review_scores_location             0
dtype: int64

También sustituí los nulos con la media, ya que esta calificación suele estar bien distribuida y el promedio mantiene representatividad.

In [46]:
#Convertir DataFrame a CSV
df.to_csv("Act 3.3 valores nulos barcelona.csv")

finalmete lo covertí a CSV

VALORES NULOS MÉXICO

In [47]:
df = pd.read_csv("MÉXICO1.csv")

In [48]:
df.shape

(26401, 51)

In [49]:
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,NaN,Entire villa,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,NaN,Entire home,Entire home/apt,...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,NaN,Entire condo,Entire home/apt,...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,NaN,Entire condo,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.isnull().sum()

Unnamed: 0                          0
id                                  0
scrape_id                           0
host_id                             0
latitude                            0
longitude                           0
neighbourhood_cleansed              0
neighbourhood_group_cleansed    26401
property_type                       0
room_type                           0
host_since                        914
host_location                    6237
host_response_time               4686
host_response_rate               4686
host_acceptance_rate             3610
host_is_superhost                1359
host_listings_count               914
host_total_listings_count         914
host_has_profile_pic              914
host_identity_verified            914
accommodates                        0
bathrooms                        3281
bathrooms_text                     31
bedrooms                          924
beds                             3297
amenities                           0
price                            3274
minimum_nights                      0
maximum_nights                      0
minimum_minimum_nights             20
maximum_minimum_nights             20
minimum_maximum_nights             20
maximum_maximum_nights             20
minimum_nights_avg_ntm              0
maximum_nights_avg_ntm              0
has_availability                 1000
availability_30                     0
availability_60                     0
availability_90                     0
availability_365                    0
availability_eoy                    0
number_of_reviews                   0
number_of_reviews_ltm               0
number_of_reviews_l30d              0
number_of_reviews_ly                0
reviews_per_month                3373
review_scores_rating             3373
review_scores_accuracy           3375
review_scores_cleanliness        3375
review_scores_communication      3375
review_scores_location           3375
dtype: int64

In [51]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(20)

neighbourhood_group_cleansed    100.000000
host_location                    23.624105
host_response_time               17.749328
host_response_rate               17.749328
host_acceptance_rate             13.673724
review_scores_location           12.783607
review_scores_communication      12.783607
review_scores_cleanliness        12.783607
review_scores_accuracy           12.783607
review_scores_rating             12.776031
reviews_per_month                12.776031
beds                             12.488163
bathrooms                        12.427560
price                            12.401045
host_is_superhost                 5.147532
has_availability                  3.787735
bedrooms                          3.499867
host_listings_count               3.461990
host_since                        3.461990
host_total_listings_count         3.461990
dtype: float64

In [52]:
df = df.drop(["neighbourhood_group_cleansed",], axis=1)
df = df.drop(["Unnamed: 0",], axis=1)

In [53]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(20)

host_location                  23.624105
host_response_time             17.749328
host_response_rate             17.749328
host_acceptance_rate           13.673724
review_scores_location         12.783607
review_scores_communication    12.783607
review_scores_cleanliness      12.783607
review_scores_accuracy         12.783607
review_scores_rating           12.776031
reviews_per_month              12.776031
beds                           12.488163
bathrooms                      12.427560
price                          12.401045
host_is_superhost               5.147532
has_availability                3.787735
bedrooms                        3.499867
host_total_listings_count       3.461990
host_has_profile_pic            3.461990
host_identity_verified          3.461990
host_since                      3.461990
dtype: float64

In [54]:
df[["host_location", "host_response_rate", "host_response_time", "review_scores_accuracy", "review_scores_location",
    "reviews_per_month", "review_scores_rating", "review_scores_communication", "review_scores_cleanliness",
    "host_acceptance_rate", "beds", "price", "bathrooms","host_is_superhost", "has_availability",
    "bedrooms", "bathrooms_text", "host_has_profile_pic", "host_total_listings_count", "host_listings_count"]].dtypes

host_location                   object
host_response_rate              object
host_response_time              object
review_scores_accuracy         float64
review_scores_location         float64
reviews_per_month              float64
review_scores_rating           float64
review_scores_communication    float64
review_scores_cleanliness      float64
host_acceptance_rate            object
beds                           float64
price                           object
bathrooms                      float64
host_is_superhost               object
has_availability                object
bedrooms                       float64
bathrooms_text                  object
host_has_profile_pic            object
host_total_listings_count      float64
host_listings_count            float64
dtype: object

In [55]:
df["host_location"].value_counts().head(5)

host_location
Mexico City, Mexico         16517
Mexico                        753
Ciudad de México, Mexico      332
Ciudad de Mexico, Mexico      190
New York, NY                  184
Name: count, dtype: int64

In [56]:
#Para rellenar HOST_LOCATION ocuparé un forward fill ya que en su mayoría los datos capturados en la base de datos
#original provienen de New Orleans, LA.

#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df["host_location"] =df["host_location"].fillna(method="ffill")
df

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/3910145857.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_location"] =df["host_location"].fillna(method="ffill")

,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,property_type,room_type,host_since,host_location,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,Entire villa,Entire home/apt,2010-06-28,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,Entire home,Entire home/apt,2010-08-09,"Mexico City, Mexico",...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,Entire condo,Entire home/apt,2010-10-19,"Mexico City, Mexico",...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,Entire rental unit,Entire home/apt,2011-01-04,"Mexico City, Mexico",...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,Entire rental unit,Entire home/apt,2010-08-24,"Mexico City, Mexico",...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,Entire condo,Entire home/apt,2018-01-28,"Mexico City, Mexico",...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,Entire rental unit,Entire home/apt,2020-07-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,Entire rental unit,Entire home/apt,2024-08-04,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,Entire loft,Entire home/apt,2014-11-25,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,Entire rental unit,Entire home/apt,2025-06-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df["host_response_rate"].value_counts().head(5)

host_response_rate
100%    17175
0%        641
99%       584
90%       481
97%       317
Name: count, dtype: int64

In [58]:
#Para host_response_rate ocuparé la moda, ya que los datos faltantes representan el 22%, existe una clara moda con
#el valor de 100% y en la lista completa hay dispersión, por lo cual usar la media no sería tan óptimo.

#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto
df["host_response_rate"]= df["host_response_rate"].fillna("100%")
df

,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,property_type,room_type,host_since,host_location,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,Entire villa,Entire home/apt,2010-06-28,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,Entire home,Entire home/apt,2010-08-09,"Mexico City, Mexico",...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,Entire condo,Entire home/apt,2010-10-19,"Mexico City, Mexico",...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,Entire rental unit,Entire home/apt,2011-01-04,"Mexico City, Mexico",...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,Entire rental unit,Entire home/apt,2010-08-24,"Mexico City, Mexico",...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,Entire condo,Entire home/apt,2018-01-28,"Mexico City, Mexico",...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,Entire rental unit,Entire home/apt,2020-07-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,Entire rental unit,Entire home/apt,2024-08-04,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,Entire loft,Entire home/apt,2014-11-25,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,Entire rental unit,Entire home/apt,2025-06-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df["host_response_rate"].isna().sum()

np.int64(0)

In [60]:
df["host_response_time"].value_counts()

host_response_time
within an hour        17811
within a few hours     1932
within a day           1060
a few days or more      912
Name: count, dtype: int64

In [61]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
df["host_response_time"] =df["host_response_time"].fillna(method="bfill")
df

/var/folders/dh/cmb1ntws385frzlj801tcrjc0000gn/T/ipykernel_7695/2823499583.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["host_response_time"] =df["host_response_time"].fillna(method="bfill")

,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,property_type,room_type,host_since,host_location,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,Entire villa,Entire home/apt,2010-06-28,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,Entire home,Entire home/apt,2010-08-09,"Mexico City, Mexico",...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,Entire condo,Entire home/apt,2010-10-19,"Mexico City, Mexico",...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,Entire rental unit,Entire home/apt,2011-01-04,"Mexico City, Mexico",...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,Entire rental unit,Entire home/apt,2010-08-24,"Mexico City, Mexico",...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,Entire condo,Entire home/apt,2018-01-28,"Mexico City, Mexico",...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,Entire rental unit,Entire home/apt,2020-07-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,Entire rental unit,Entire home/apt,2024-08-04,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,Entire loft,Entire home/apt,2014-11-25,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,Entire rental unit,Entire home/apt,2025-06-24,"Mexico City, Mexico",...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df["host_response_time"].isna().sum()

np.int64(1)

In [63]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(15)

host_acceptance_rate           13.673724
review_scores_location         12.783607
review_scores_communication    12.783607
review_scores_cleanliness      12.783607
review_scores_accuracy         12.783607
review_scores_rating           12.776031
reviews_per_month              12.776031
beds                           12.488163
bathrooms                      12.427560
price                          12.401045
host_is_superhost               5.147532
has_availability                3.787735
bedrooms                        3.499867
host_listings_count             3.461990
host_total_listings_count       3.461990
dtype: float64

In [64]:
df["review_scores_accuracy"].value_counts()

review_scores_accuracy
5.00    4817
4.88     767
4.93     701
4.94     683
4.89     682
        ...
3.64       1
2.89       1
4.02       1
3.93       1
3.14       1
Name: count, Length: 146, dtype: int64

In [65]:
df["review_scores_accuracy"].describe()

count    23026.000000
mean         4.782467
std          0.369792
min          1.000000
25%          4.750000
50%          4.880000
75%          4.960000
max          5.000000
Name: review_scores_accuracy, dtype: float64

In [66]:
#EN ESTE CASO SUSTITUIRÉ DE MANERA MANUAL PARA NO MODIFICAR EL #Sustituir valores nulos por un valor numérico en  concreto
df["review_scores_accuracy"]= df["review_scores_accuracy"].fillna("0")

In [67]:
df["review_scores_accuracy"].isna().sum()

np.int64(0)

In [68]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(14)

host_acceptance_rate           13.673724
review_scores_location         12.783607
review_scores_communication    12.783607
review_scores_cleanliness      12.783607
review_scores_rating           12.776031
reviews_per_month              12.776031
beds                           12.488163
bathrooms                      12.427560
price                          12.401045
host_is_superhost               5.147532
has_availability                3.787735
bedrooms                        3.499867
host_identity_verified          3.461990
host_since                      3.461990
dtype: float64

In [69]:
df["review_scores_location"].describe()

count    23026.000000
mean         4.840647
std          0.298201
min          1.000000
25%          4.800000
50%          4.920000
75%          5.000000
max          5.000000
Name: review_scores_location, dtype: float64

In [70]:
df["review_scores_location"].value_counts()

review_scores_location
5.00    6188
4.94     872
4.96     863
4.95     804
4.93     798
        ...
3.65       1
4.12       1
3.83       1
2.60       1
1.50       1
Name: count, Length: 128, dtype: int64

In [71]:
#EN ESTE CASO SUSTITUIRÉ DE MANERA MANUAL PARA NO MODIFICAR EL #Sustituir valores nulos por un valor numérico en  concreto
df["review_scores_location"]= df["review_scores_location"].fillna("0")

In [72]:
df["review_scores_location"].isna().sum()

np.int64(0)

In [73]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(15)

host_acceptance_rate           13.673724
review_scores_communication    12.783607
review_scores_cleanliness      12.783607
review_scores_rating           12.776031
reviews_per_month              12.776031
beds                           12.488163
bathrooms                      12.427560
price                          12.401045
host_is_superhost               5.147532
has_availability                3.787735
bedrooms                        3.499867
host_listings_count             3.461990
host_identity_verified          3.461990
host_total_listings_count       3.461990
host_has_profile_pic            3.461990
dtype: float64

In [74]:
#A partir de este momento, me di cuenta que hay cuatro valores con exactamente la misma cantidad de datos faltantes, y analizando la base de datos
#original, el tipo de datos faltantes es parecido. Por lo tanto, estaré rellenando con 0 para no modificar el comportamiento de la información og.

df["review_scores_rating"]= df["review_scores_rating"].fillna("0")
df["reviews_per_month"]= df["reviews_per_month"].fillna("0")
df["review_scores_cleanliness"]= df["review_scores_cleanliness"].fillna("0")
df["review_scores_communication"]= df["review_scores_communication"].fillna("0")

In [75]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(10)

host_acceptance_rate         13.673724
beds                         12.488163
bathrooms                    12.427560
price                        12.401045
host_is_superhost             5.147532
has_availability              3.787735
bedrooms                      3.499867
host_identity_verified        3.461990
host_total_listings_count     3.461990
host_listings_count           3.461990
dtype: float64

In [76]:
df[["host_acceptance_rate", "beds", "price", "bathrooms","host_is_superhost", "has_availability",
    "bedrooms", "bathrooms_text"]].dtypes

host_acceptance_rate     object
beds                    float64
price                    object
bathrooms               float64
host_is_superhost        object
has_availability         object
bedrooms                float64
bathrooms_text           object
dtype: object

In [77]:
df["host_acceptance_rate"].value_counts()

host_acceptance_rate
100%    10909
99%      2865
98%      1434
0%       1062
97%       795
        ...
15%         3
10%         2
23%         2
26%         1
28%         1
Name: count, Length: 100, dtype: int64

In [78]:
df["host_acceptance_rate"]= df["host_acceptance_rate"].fillna("0")

In [79]:
df["beds"].mode()

0    1.0
Name: beds, dtype: float64

In [80]:
#para este valor ocuparé la moda
df["beds"]= df["beds"].fillna("2")

In [81]:
df["price"]= df["price"].fillna("0")

In [82]:
#para el caso del precio, decidí dejarla en valores de 0 ya que existe mucha dispersión, por lo tanto no habría información verosímil si lo reempazara
#por alguna medida de tendencia central
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(6)

bathrooms                    12.427560
host_is_superhost             5.147532
has_availability              3.787735
bedrooms                      3.499867
host_total_listings_count     3.461990
host_since                    3.461990
dtype: float64

In [83]:
df["bathrooms"].describe()

count    23120.000000
mean         1.450389
std          1.033995
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         49.000000
Name: bathrooms, dtype: float64

In [84]:
#Para la parte de baños, decidí colocar 1, ya que mínimo deben tener un baño, además de que la moda es ese valor
df["bathrooms"]= df["bathrooms"].fillna("1")

In [85]:
df["host_is_superhost"].value_counts()

host_is_superhost
f    15365
t     9677
Name: count, dtype: int64

In [86]:
#Apartir de aquí imputaré con medidas de tendencia central ya que el porcentaje faltante es menor al 5%
df["host_is_superhost"]= df["host_is_superhost"].fillna("f")

In [87]:
df["has_availability"].describe()
df["has_availability"]= df["has_availability"].fillna("t")

In [88]:
df["bedrooms"]= df["bedrooms"].fillna("1")

In [89]:
df["bathrooms_text"]= df["bathrooms_text"].fillna("1 bath")

In [90]:
#CONOCER EL PORCENTAJE DE MISSING VALUES POR COLUMNA
porcentaje_missing = (df.isna().mean() * 100).sort_values(ascending=False)
porcentaje_missing.head(5)

host_listings_count          3.46199
host_since                   3.46199
host_identity_verified       3.46199
host_has_profile_pic         3.46199
host_total_listings_count    3.46199
dtype: float64

In [91]:
df.to_csv("MÉXICO_CLEAN.csv")