In [29]:
#INSTALAR LIBRERIAS
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install seaborn
%pip install openpyxl

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sofiavillar/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
#Convertir en dataframe
df= pd.read_csv('Actividad 1 Entendimiento de los Datos.csv')
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

Los registros de 5 “host name” diferentes

In [32]:
#  a) Primeros 5 host_name diferentes
cinco_hosts = df["property_type"].unique()
cinco_hosts

array(['Entire rental unit', 'Entire condo', 'Entire home',
       'Private room in rental unit', 'Entire vacation home',
       'Entire serviced apartment', 'Entire loft',
       'Private room in condo', 'Private room in loft',
       'Entire townhouse', 'Private room in guest suite',
       'Private room in floor', 'Private room in bed and breakfast',
       'Private room in home', 'Room in serviced apartment',
       'Private room in casa particular', 'Entire villa',
       'Private room in guesthouse', 'Private room in hostel',
       'Private room in serviced apartment', 'Tiny home',
       'Private room in dome', 'Room in aparthotel',
       'Shared room in hostel', 'Room in boutique hotel',
       'Entire guesthouse', 'Entire guest suite', 'Entire cabin', 'Barn',
       'Private room', 'Private room in chalet', 'Private room in villa',
       'Private room in townhouse', 'Entire place',
       'Private room in boat', 'Room in hostel', 'Room in hotel',
       'Room in bed and breakfast', 'Boat', 'Entire chalet',
       'Casa particular', 'Camper/RV', 'Dome',
       'Private room in tiny home', 'Shared room in rental unit',
       'Shared room in boutique hotel', 'Private room in cottage',
       'Shared room in hotel', 'Entire hostel',
       'Shared room in guesthouse', 'Shared room in home',
       'Shipping container'], dtype=object)

In [33]:
tipos_elegidos = ["Room in boutique hotel", "Entire townhouse", "Entire rental unit", "Entire guest suite", "Private room in home",] 
a_result = df[df["property_type"].isin(tipos_elegidos)]
a_result
df1 = a_result.groupby(['property_type'])['property_type'].count()
df1

property_type
Entire guest suite           26
Entire rental unit        10416
Entire townhouse             18
Private room in home        206
Room in boutique hotel      177
Name: property_type, dtype: int64

In [34]:
f1=a_result.to_csv("fltro01.csv", index=False)

Los registros de los host que se hallan unido a Airbnb “despues del año 2020”

In [35]:
# b) Host_since > 2020
df["host_since"] = pd.to_datetime(df["host_since"], errors="coerce")
b_result = df[df["host_since"] >= "2021-01-01"]
b_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
839,839,2670047,20250612050654,510942439,41.374390,2.160140,el Poble Sec,Sants-Montjuïc,Entire rental unit,Entire home/apt,...,478,20,3,20,3.51,4.76,4.82,4.74,4.87,4.71
1019,1019,3189694,20250612050654,510942439,41.373570,2.164020,el Poble Sec,Sants-Montjuïc,Entire rental unit,Entire home/apt,...,313,42,3,50,2.63,4.63,4.71,4.71,4.83,4.69
1460,1460,5429860,20250612050654,437835392,41.404260,2.173640,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,17,1,0,2,0.14,4.47,4.41,4.41,4.76,4.94
2144,2144,11814469,20250612050654,510942439,41.401420,2.160760,la Vila de Gràcia,Gràcia,Entire rental unit,Entire home/apt,...,264,27,1,32,2.35,4.67,4.77,4.75,4.85,4.91
2414,2414,13572127,20250612050654,537105282,41.407370,2.166260,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,194,46,3,51,2.04,4.75,4.80,4.68,4.85,4.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18900,18900,1438993628662440481,20250612050654,528129368,41.379177,2.166336,el Raval,Ciutat Vella,Private room in home,Private room,...,2,2,2,0,2.00,5.00,5.00,5.00,5.00,5.00
18901,18901,1438997373129491299,20250612050654,528129368,41.379960,2.166359,el Raval,Ciutat Vella,Private room in home,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
18902,18902,1439000638187447126,20250612050654,528129368,41.378966,2.165534,el Raval,Ciutat Vella,Private room in home,Private room,...,2,2,2,0,2.00,4.00,4.00,3.50,5.00,5.00
18903,18903,1439004190948739706,20250612050654,514124696,41.378440,2.167370,el Raval,Ciutat Vella,Private room in home,Private room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18915,18915,1439876945348295255,20250612050654,528129368,41.380060,2.168240,el Raval,Ciutat Vella,Private room in home,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18927 entries, 0 to 18926
Data columns (total 51 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    18927 non-null  int64
 1   id                            18927 non-null  int64
 2   scrape_id                     18927 non-null  int64
 3   host_id                       18927 non-null  int64
 4   latitude                      18927 non-null  float64
 5   longitude                     18927 non-null  float64
 6   neighbourhood_cleansed        18927 non-null  object
 7   neighbourhood_group_cleansed  18927 non-null  object
 8   property_type                 18927 non-null  object
 9   room_type                     18927 non-null  object
 10  host_since                    18924 non-null  datetime64[ns]
 11  host_location                 14551 non-null  object
 12  host_response_time            16037 non-null  object
 13  host_response_rate            16037 non-null  object
 14  host_acceptance_rate          16183 non-null  object
 15  host_is_superhost             18360 non-null  object
 16  host_listings_count           18924 non-null  float64
 17  host_total_listings_count     18924 non-null  float64
 18  host_has_profile_pic          18924 non-null  object
 19  host_identity_verified        18924 non-null  object
 20  accommodates                  18927 non-null  int64
 21  bathrooms                     14942 non-null  float64
 22  bathrooms_text                18919 non-null  object
 23  bedrooms                      16870 non-null  float64
 24  beds                          14874 non-null  float64
 25  amenities                     18927 non-null  object
 26  price                         14913 non-null  object
 27  minimum_nights                18927 non-null  int64
 28  maximum_nights                18927 non-null  int64
 29  minimum_minimum_nights        18923 non-null  float64
 30  maximum_minimum_nights        18923 non-null  float64
 31  minimum_maximum_nights        18923 non-null  float64
 32  maximum_maximum_nights        18923 non-null  float64
 33  minimum_nights_avg_ntm        18927 non-null  float64
 34  maximum_nights_avg_ntm        18927 non-null  float64
 35  has_availability              17838 non-null  object
 36  availability_30               18927 non-null  int64
 37  availability_60               18927 non-null  int64
 38  availability_90               18927 non-null  int64
 39  availability_365              18927 non-null  int64
 40  availability_eoy              18927 non-null  int64
 41  number_of_reviews             18927 non-null  int64
 42  number_of_reviews_ltm         18927 non-null  int64
 43  number_of_reviews_l30d        18927 non-null  int64
 44  number_of_reviews_ly          18927 non-null  int64
 45  reviews_per_month             13929 non-null  float64
 46  review_scores_rating          13929 non-null  float64
 47  review_scores_accuracy        13926 non-null  float64
 48  review_scores_cleanliness     13927 non-null  float64
 49  review_scores_communication   13928 non-null  float64
 50  review_scores_location        13926 non-null  float64
dtypes: datetime64[ns](1), float64(19), int64(16), object(15)
memory usage: 7.4+ MB

In [37]:
df2 = b_result.groupby(['host_since'])['host_since'].count()
df2

host_since
2021-01-06    1
2021-01-09    1
2021-01-11    2
2021-01-13    1
2021-01-14    5
             ..
2025-05-16    1
2025-05-19    3
2025-05-26    4
2025-06-04    1
2025-06-11    2
Name: host_since, Length: 877, dtype: int64

In [38]:
f2=b_result.to_csv("filtro02.csv", index=False)

Los registros de los host que responden “a más tardar en 1 día"

In [39]:
# c) Respuesta rápida (en 1 día o menos)
df3 = df.groupby(['host_response_time'])['host_response_time'].count()
df3

host_response_time
a few days or more      531
within a day           1576
within a few hours     2794
within an hour        11136
Name: host_response_time, dtype: int64

Los registros de las filas “Múltiplos de 200… (400, 600, 800, etc.

In [40]:
# c) Respuesta rápida (en 1 día o menos)
rapidas = ["within an hour", "within a few hours", "within a day"]
c_result = df[df["host_response_time"].str.lower().isin(rapidas)]
c_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
f3=c_result.to_csv("filtro03.csv", index=False)

Los registros de las filas “Múltiplos de 200… (400, 600, 800, etc.)”

In [42]:
filas= df.iloc[0::200,:] 
filas

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
200,200,694516,20250612050654,3019128,41.425930,2.167480,la Font d'en Fargues,Horta-Guinardó,Entire condo,Entire home/apt,...,62,4,1,4,0.40,4.87,4.92,4.84,4.87,4.71
400,400,1085376,20250612050654,5966973,41.395780,2.181310,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,547,46,4,48,3.73,4.55,4.60,4.53,4.75,4.81
600,600,1330353,20250612050654,3799101,41.397790,2.159040,la Vila de Gràcia,Gràcia,Entire rental unit,Entire home/apt,...,76,12,1,18,1.84,4.89,4.88,4.82,4.87,4.93
800,800,2512546,20250612050654,3038266,41.392840,2.165760,la Dreta de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,483,61,4,56,3.55,4.86,4.90,4.89,4.88,4.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18000,18000,1384093592412591162,20250612050654,571289218,41.380510,2.163220,Sant Antoni,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18200,18200,1392034344774768888,20250612050654,1447144,41.380300,2.148670,la Nova Esquerra de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18400,18400,1407987673919415813,20250612050654,15775899,41.391032,2.175454,la Dreta de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,2,2,2,0,2.00,5.00,5.00,5.00,5.00,5.00
18600,18600,1421600544718703815,20250612050654,212552215,41.377272,2.167641,el Raval,Ciutat Vella,Private room in rental unit,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00
18800,18800,1434846226016277801,20250612050654,396940257,41.419931,2.212714,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
f4=filas.to_csv("filtro04.csv", index=False)

Los registros de los tipos de cuarto: “Entire home” y “Private room”

In [44]:
df4 = df.groupby(['room_type'])['room_type'].count()
df4

room_type
Entire home/apt    11657
Hotel room            91
Private room        7087
Shared room           92
Name: room_type, dtype: int64

In [45]:
# e) Filtrar tipos de cuarto específicos
permitidos = ["entire home/apt", "private room"]
e_result = df[df["room_type"].str.lower().isin(permitidos)]
e_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,18674,20250612050654,71615,41.405560,2.172620,la Sagrada Família,Eixample,Entire rental unit,Entire home/apt,...,48,6,2,5,0.33,4.30,4.36,4.53,4.60,4.81
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.170150,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.175170,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.191020,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,1440378586135901437,20250612050654,4459553,41.399220,2.178950,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18923,18923,1440379191108051829,20250612050654,4459553,41.399790,2.180350,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18924,18924,1440379869744969989,20250612050654,4459553,41.399390,2.180520,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18925,18925,1440380503685655376,20250612050654,4459553,41.400813,2.180756,el Fort Pienc,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18926,18926,1440381140081945750,20250612050654,4459553,41.410760,2.179390,el Camp de l'Arpa del Clot,Sant Martí,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
f5=e_result.to_csv("filtro05.csv", index=False)

Los registros que “a lo mucho cuenten con 4 camas”

In [47]:
df5 = df.groupby(['beds'])['beds'].count()
df5

beds
0.0       264
1.0      5444
2.0      3201
3.0      2559
4.0      1654
5.0       747
6.0       464
7.0       221
8.0       105
9.0        54
10.0       51
11.0       10
12.0       23
13.0       13
14.0       10
15.0       19
16.0        9
17.0        1
18.0        5
19.0        2
20.0        6
22.0        1
23.0        1
24.0        2
25.0        3
26.0        1
27.0        1
30.0        1
32.0        1
127.0       1
Name: beds, dtype: int64

In [48]:
# f) Filtro por número de camas
df["beds"] = pd.to_numeric(df["beds"], errors="coerce")
f_result = df[df["beds"] <= 4]
f_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
1,1,23197,20250612050654,90417,41.412432,2.21975,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
2,2,32711,20250612050654,135703,41.405660,2.17015,el Camp d'en Grassot i Gràcia Nova,Gràcia,Entire rental unit,Entire home/apt,...,147,26,0,37,0.87,4.46,4.44,4.38,4.89,4.89
3,3,34241,20250612050654,73163,41.380620,2.17517,el Barri Gòtic,Ciutat Vella,Entire condo,Entire home/apt,...,25,9,0,17,0.14,4.36,4.45,4.55,4.68,4.73
4,4,347824,20250612050654,1447144,41.376400,2.19102,la Barceloneta,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,0,0,1,0.02,4.00,4.67,4.00,3.67,5.00
6,6,352772,20250612050654,1786501,41.381840,2.15119,la Nova Esquerra de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,276,42,5,41,2.00,4.76,4.79,4.68,4.78,4.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18917,18917,1439929163301654408,20250612050654,333769431,41.386900,2.13452,les Corts,Les Corts,Private room in rental unit,Private room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18918,18918,1439973901383651503,20250612050654,13530812,41.382000,2.18411,"Sant Pere, Santa Caterina i la Ribera",Ciutat Vella,Private room in rental unit,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00
18919,18919,1439984636030445391,20250612050654,18191427,41.389720,2.16239,la Dreta de l'Eixample,Eixample,Private room in rental unit,Private room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18920,18920,1440194065487969705,20250612050654,325642121,41.385540,2.16688,el Raval,Ciutat Vella,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18921,18921,1440349155331196931,20250612050654,49813494,41.381660,2.17984,el Barri Gòtic,Ciutat Vella,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
f6=f_result.to_csv("filtro05.csv", index=False)

Los registros que “sean superhost”

In [50]:
df6 = df.groupby(['host_is_superhost'])['host_is_superhost'].count()
df6

host_is_superhost
f    14234
t     4126
Name: host_is_superhost, dtype: int64

In [51]:
# g) Filtro por superhost
g_result = df[df["host_is_superhost"] == "t"]   # o True si ya está como boolean
g_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
1,1,23197,20250612050654,90417,41.412432,2.219750,el Besòs i el Maresme,Sant Martí,Entire rental unit,Entire home/apt,...,88,10,1,7,0.51,4.82,4.94,4.90,4.99,4.65
5,5,351395,20250612050654,1435464,41.392710,2.179740,el Fort Pienc,Eixample,Entire condo,Entire home/apt,...,108,17,2,13,0.74,4.62,4.63,4.64,4.74,4.77
6,6,352772,20250612050654,1786501,41.381840,2.151190,la Nova Esquerra de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,276,42,5,41,2.00,4.76,4.79,4.68,4.78,4.75
8,8,357576,20250612050654,1809535,41.405080,2.154910,la Vila de Gràcia,Gràcia,Entire home,Entire home/apt,...,500,65,4,74,3.16,4.91,4.93,4.93,4.99,4.96
19,19,384464,20250612050654,674212,41.389920,2.169740,la Dreta de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,228,0,0,8,1.42,4.97,4.98,4.98,4.99,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18874,18874,1436476640139020572,20250612050654,573682415,41.381748,2.174976,el Barri Gòtic,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,3,3,0,3.00,5.00,5.00,5.00,5.00,5.00
18875,18875,1436479418387294109,20250612050654,573682415,41.381720,2.168940,el Raval,Ciutat Vella,Entire rental unit,Entire home/apt,...,3,3,3,0,3.00,5.00,5.00,5.00,5.00,5.00
18876,18876,1436504753464828109,20250612050654,4959266,41.383240,2.178510,el Barri Gòtic,Ciutat Vella,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18880,18880,1440886957702009698,20250612050654,325642121,41.387350,2.167790,la Dreta de l'Eixample,Eixample,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18920,18920,1440194065487969705,20250612050654,325642121,41.385540,2.166880,el Raval,Ciutat Vella,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
f7=g_result.to_csv("filtro07.csv", index=False)

Los registros de las columnas “impares”

In [53]:
# h) Columnas en posiciones impares (1, 3, 5…)
odd_cols = [col for i, col in enumerate(df.columns, start=1) if i % 2 == 1]
h_result = df[odd_cols]
h_result

,Unnamed: 0,scrape_id,latitude,neighbourhood_cleansed,property_type,host_since,host_response_time,host_acceptance_rate,host_listings_count,host_has_profile_pic,...,maximum_maximum_nights,maximum_nights_avg_ntm,availability_30,availability_90,availability_eoy,number_of_reviews_ltm,number_of_reviews_ly,review_scores_rating,review_scores_cleanliness,review_scores_location
0,0,20250612050654,41.405560,la Sagrada Família,Entire rental unit,2010-01-19,within an hour,91%,44.0,t,...,999.0,999.0,11,53,65,6,5,4.30,4.53,4.81
1,1,20250612050654,41.412432,el Besòs i el Maresme,Entire rental unit,2010-03-09,within an hour,96%,6.0,t,...,1125.0,1125.0,6,29,124,10,7,4.82,4.90,4.65
2,2,20250612050654,41.405660,el Camp d'en Grassot i Gràcia Nova,Entire rental unit,2010-05-31,within an hour,100%,3.0,t,...,31.0,31.0,5,31,39,26,37,4.46,4.38,4.89
3,3,20250612050654,41.380620,el Barri Gòtic,Entire condo,2010-01-24,within an hour,94%,5.0,t,...,180.0,180.0,30,90,193,9,17,4.36,4.55,4.73
4,4,20250612050654,41.376400,la Barceloneta,Entire rental unit,2011-11-27,within an hour,28%,356.0,t,...,330.0,330.0,30,90,193,0,1,4.00,4.00,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,18922,20250612050654,41.399220,el Fort Pienc,Entire rental unit,2012-12-21,within an hour,79%,224.0,t,...,365.0,83.3,6,37,129,0,0,NaN,NaN,NaN
18923,18923,20250612050654,41.399790,el Fort Pienc,Entire rental unit,2012-12-21,within an hour,79%,224.0,t,...,365.0,81.8,0,27,131,0,0,NaN,NaN,NaN
18924,18924,20250612050654,41.399390,el Fort Pienc,Entire rental unit,2012-12-21,within an hour,79%,224.0,t,...,365.0,84.4,3,36,140,0,0,NaN,NaN,NaN
18925,18925,20250612050654,41.400813,el Fort Pienc,Entire rental unit,2012-12-21,within an hour,79%,224.0,t,...,365.0,94.9,4,28,130,0,0,NaN,NaN,NaN
18926,18926,20250612050654,41.410760,el Camp de l'Arpa del Clot,Entire rental unit,2012-12-21,within an hour,79%,224.0,t,...,365.0,98.3,0,22,125,0,0,NaN,NaN,NaN

In [54]:
f8=h_result.to_csv("filtro08.csv", index=False)

EXTRACCIÓN DE DATOS MEXICO

In [55]:
#Convertir en dataframe
df= pd.read_csv('MÉXICO1.csv')
df

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,NaN,Entire villa,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,NaN,Entire home,Entire home/apt,...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,NaN,Entire condo,Entire home/apt,...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,NaN,Entire condo,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
#a) Los registros de 5 “host name” diferentes
cinco_hosts = df["property_type"].unique()
cinco_hosts
#a_result = df[df["property_type"].isin(cinco_hosts)]
#a_result.head()

array(['Entire villa', 'Entire home', 'Entire condo',
       'Entire rental unit', 'Private room',
       'Private room in rental unit', 'Entire loft',
       'Private room in home', 'Private room in condo',
       'Room in boutique hotel', 'Room in serviced apartment',
       'Entire guest suite', 'Private room in townhouse',
       'Private room in bed and breakfast', 'Private room in guest suite',
       'Entire serviced apartment', 'Entire guesthouse', 'Tiny home',
       'Private room in guesthouse', 'Entire bungalow',
       'Entire townhouse', 'Private room in loft',
       'Private room in tiny home', 'Entire cabin',
       'Room in bed and breakfast', 'Private room in farm stay',
       'Private room in serviced apartment',
       'Private room in casa particular', 'Room in hotel',
       'Private room in floor', 'Private room in cabin',
       'Room in aparthotel', 'Entire place', 'Shared room in rental unit',
       'Private room in hostel', 'Earthen home', 'Entire hostel',
       'Private room in earthen home', 'Entire cottage',
       'Shared room in home', 'Private room in villa',
       'Private room in hut', 'Entire chalet', 'Entire in-law',
       'Holiday park', 'Shared room in condo', 'Casa particular',
       'Private room in dome', 'Shared room in hostel', 'Campsite',
       'Private room in vacation home', 'Room in casa particular',
       'Castle', 'Private room in barn', 'Shared room in hotel',
       'Farm stay', 'Hut', 'Private room in cottage',
       'Private room in resort', 'Entire home/apt', 'Room in hostel',
       'Entire vacation home', 'Private room in nature lodge',
       'Private room in shipping container', 'Private room in tower',
       'Private room in lighthouse', 'Shared room in townhouse',
       'Shared room in guesthouse', 'Shipping container',
       'Shared room in bed and breakfast', 'Private room in pension',
       'Dome', 'Shared room in guest suite', 'Tent',
       'Private room in tent', 'Private room in castle',
       'Private room in houseboat', 'Shared room in casa particular',
       'Private room in minsu', 'Tower'], dtype=object)

In [57]:
# Elige 5 tipos de propiedad específicos manualmente
tipos_elegidos = ["Entire rental unit", "Entire guest suite", "Private room in home", "Room in boutique hotel", "Entire townhouse"] 

# Filtra el DataFrame para mostrar solo las observaciones que coincidan con esos tipos
a_result = df[df["property_type"].isin(tipos_elegidos)]

# Muestra todas las observaciones filtradas (no solo .head())
a_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
9,9,187030,20250625031918,899360,19.410570,-99.177300,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,103,0,0,0,0.62,4.57,4.66,4.66,4.88,4.92
10,10,1286695,20250625031918,6998716,19.435140,-99.183610,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,35,3,0,4,0.33,4.54,4.57,4.66,4.74,4.71
11,11,1288566,20250625031918,540705,19.431790,-99.194260,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,217,57,5,49,1.92,4.89,4.93,4.91,4.87,4.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26393,26393,1450244485815740442,20250625031918,431645813,19.350020,-99.164490,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26395,26395,1450293397186325322,20250625031918,180725654,19.346430,-99.127499,Coyoacán,NaN,Private room in home,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
#Analizar categorias de una columna
df1 = a_result.groupby(['property_type'])['property_type'].count()
df1

property_type
Entire guest suite          222
Entire rental unit        10130
Entire townhouse             52
Private room in home       2313
Room in boutique hotel      175
Name: property_type, dtype: int64

In [59]:
f1=a_result.to_csv("f1.csv", index=False)

In [60]:
# b) Host_since > 2020
df["host_since"] = pd.to_datetime(df["host_since"], errors="coerce")
b_result = df[df["host_since"] >= '2021-01-01']
b_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
49,49,1850394,20250625031918,456052310,19.431220,-99.155620,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,326,10,0,3,2.32,4.82,4.85,4.79,4.93,4.79
1004,1004,13113108,20250625031918,451159548,19.408640,-99.169620,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,225,16,1,8,2.18,4.63,4.78,4.60,4.86,4.96
1312,1312,15548531,20250625031918,456052310,19.425190,-99.160100,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,239,17,3,18,2.32,4.82,4.84,4.87,4.92,4.93
1517,1517,16740335,20250625031918,422844046,19.441860,-99.193000,Miguel Hidalgo,NaN,Private room in home,Private room,...,42,27,4,15,1.12,4.93,4.88,4.93,4.90,4.90
1565,1565,16884563,20250625031918,438365834,19.431483,-99.139499,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,105,26,1,21,1.03,4.87,4.92,4.86,4.97,4.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26390,26390,1450214091258204699,20250625031918,468188466,19.429398,-99.151096,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26391,26391,1450233077447172488,20250625031918,665095287,19.408996,-99.146329,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26393,26393,1450244485815740442,20250625031918,431645813,19.350020,-99.164490,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26401 entries, 0 to 26400
Data columns (total 51 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    26401 non-null  int64
 1   id                            26401 non-null  int64
 2   scrape_id                     26401 non-null  int64
 3   host_id                       26401 non-null  int64
 4   latitude                      26401 non-null  float64
 5   longitude                     26401 non-null  float64
 6   neighbourhood_cleansed        26401 non-null  object
 7   neighbourhood_group_cleansed  0 non-null      float64
 8   property_type                 26401 non-null  object
 9   room_type                     26401 non-null  object
 10  host_since                    25487 non-null  datetime64[ns]
 11  host_location                 20164 non-null  object
 12  host_response_time            21715 non-null  object
 13  host_response_rate            21715 non-null  object
 14  host_acceptance_rate          22791 non-null  object
 15  host_is_superhost             25042 non-null  object
 16  host_listings_count           25487 non-null  float64
 17  host_total_listings_count     25487 non-null  float64
 18  host_has_profile_pic          25487 non-null  object
 19  host_identity_verified        25487 non-null  object
 20  accommodates                  26401 non-null  int64
 21  bathrooms                     23120 non-null  float64
 22  bathrooms_text                26370 non-null  object
 23  bedrooms                      25477 non-null  float64
 24  beds                          23104 non-null  float64
 25  amenities                     26401 non-null  object
 26  price                         23127 non-null  object
 27  minimum_nights                26401 non-null  int64
 28  maximum_nights                26401 non-null  int64
 29  minimum_minimum_nights        26381 non-null  float64
 30  maximum_minimum_nights        26381 non-null  float64
 31  minimum_maximum_nights        26381 non-null  float64
 32  maximum_maximum_nights        26381 non-null  float64
 33  minimum_nights_avg_ntm        26401 non-null  float64
 34  maximum_nights_avg_ntm        26401 non-null  float64
 35  has_availability              25401 non-null  object
 36  availability_30               26401 non-null  int64
 37  availability_60               26401 non-null  int64
 38  availability_90               26401 non-null  int64
 39  availability_365              26401 non-null  int64
 40  availability_eoy              26401 non-null  int64
 41  number_of_reviews             26401 non-null  int64
 42  number_of_reviews_ltm         26401 non-null  int64
 43  number_of_reviews_l30d        26401 non-null  int64
 44  number_of_reviews_ly          26401 non-null  int64
 45  reviews_per_month             23028 non-null  float64
 46  review_scores_rating          23028 non-null  float64
 47  review_scores_accuracy        23026 non-null  float64
 48  review_scores_cleanliness     23026 non-null  float64
 49  review_scores_communication   23026 non-null  float64
 50  review_scores_location        23026 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(16), object(14)
memory usage: 10.3+ MB

In [62]:
df2 = b_result.groupby(['host_since'])['host_since'].count()
df2

host_since
2021-01-01    5
2021-01-02    1
2021-01-03    1
2021-01-04    1
2021-01-05    6
             ..
2025-06-14    1
2025-06-16    4
2025-06-17    1
2025-06-18    1
2025-06-24    1
Name: host_since, Length: 1297, dtype: int64

In [63]:
f2=b_result.to_csv("f2.csv", index=False)

In [64]:
df3 = df.groupby(['host_response_time'])['host_response_time'].count()
df3

host_response_time
a few days or more      912
within a day           1060
within a few hours     1932
within an hour        17811
Name: host_response_time, dtype: int64

In [65]:
# c) Respuesta rápida (en 1 día o menos)
rapidas = ["within an hour", "within a few hours", "within a day"]
c_result = df[df["host_response_time"].str.lower().isin(rapidas)]
c_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
1,1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,NaN,Entire home,Entire home/apt,...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,NaN,Entire condo,Entire home/apt,...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
6,6,165772,20250625031918,790208,19.408260,-99.186590,Miguel Hidalgo,NaN,Entire home,Entire home/apt,...,383,31,0,38,2.26,4.88,4.91,4.83,4.88,4.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26395,26395,1450293397186325322,20250625031918,180725654,19.346430,-99.127499,Coyoacán,NaN,Private room in home,Private room,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00
26396,26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,NaN,Entire condo,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
f3=c_result.to_csv("f3.csv", index=False)

In [67]:
#Filas incrementales en un fator
filas= df.iloc[0::200,:] #Filas con incrementos de 100 a partir de la fila 0 
filas

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,NaN,Entire villa,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
200,200,4814757,20250625031918,12389380,19.438150,-99.136440,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,60,8,0,6,0.49,4.72,4.82,4.72,4.88,4.71
400,400,6572854,20250625031918,34377738,19.311030,-99.225330,La Magdalena Contreras,NaN,Private room in rental unit,Private room,...,10,0,0,0,0.08,4.70,4.90,4.90,4.90,5.00
600,600,8993396,20250625031918,5085423,19.444020,-99.204390,Miguel Hidalgo,NaN,Entire condo,Entire home/apt,...,25,1,0,0,0.21,4.92,5.00,4.87,5.00,5.00
800,800,11507601,20250625031918,35406862,19.425430,-99.171760,Cuauhtémoc,NaN,Room in serviced apartment,Hotel room,...,2,0,0,0,0.02,5.00,5.00,5.00,5.00,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25600,25600,1422624281706600621,20250625031918,695536587,19.426650,-99.160120,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
25800,25800,1434316794866247356,20250625031918,367698783,19.471717,-99.123603,Gustavo A. Madero,NaN,Private room in home,Private room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26000,26000,1440073609853187910,20250625031918,440195875,19.414780,-99.162810,Cuauhtémoc,NaN,Shared room in guesthouse,Shared room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26200,26200,1444979774990771506,20250625031918,698035372,19.435138,-99.199584,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
f4=filas.to_csv("f4.csv", index=False)

In [69]:
df4 = df.groupby(['room_type'])['room_type'].count()
df4

room_type
Entire home/apt    17235
Hotel room            91
Private room        8867
Shared room          208
Name: room_type, dtype: int64

In [70]:
# e) Filtrar tipos de cuarto específicos
permitidos = ["entire home/apt", "private room"]
e_result = df[df["room_type"].str.lower().isin(permitidos)]
e_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,NaN,Entire villa,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,44616,20250625031918,196253,19.411620,-99.177940,Cuauhtémoc,NaN,Entire home,Entire home/apt,...,65,1,0,0,0.39,4.59,4.56,4.70,4.78,4.98
2,2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,NaN,Entire condo,Entire home/apt,...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,NaN,Entire condo,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
f5=e_result.to_csv("f5.csv", index=False)

In [72]:
df5 = df.groupby(['beds'])['beds'].count()
df5

beds
0.0       361
1.0     11421
2.0      6251
3.0      2791
4.0      1177
5.0       425
6.0       242
7.0       111
8.0        97
9.0        63
10.0       40
11.0       25
12.0       26
13.0        8
14.0       11
15.0        6
16.0       12
17.0        5
18.0        2
19.0        2
20.0        3
21.0        4
22.0        4
23.0        1
24.0        5
25.0        2
26.0        2
28.0        1
30.0        2
35.0        1
40.0        1
50.0        2
Name: beds, dtype: int64

In [73]:
# f) Filtro por número de camas
df["beds"] = pd.to_numeric(df["beds"], errors="coerce")
f_result = df[df["beds"] <= 4]
f_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
0,0,35797,20250625031918,153786,19.382830,-99.271780,Cuajimalpa de Morelos,NaN,Entire villa,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,56074,20250625031918,265650,19.439770,-99.156050,Cuauhtémoc,NaN,Entire condo,Entire home/apt,...,84,1,0,0,0.48,4.87,4.95,4.88,4.94,4.76
3,3,67703,20250625031918,334451,19.411520,-99.168570,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,50,1,0,4,0.30,4.90,4.82,4.76,4.92,4.98
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
7,7,171109,20250625031918,816295,19.396750,-99.175810,Benito Juárez,NaN,Private room in rental unit,Private room,...,117,10,3,7,0.85,4.84,4.86,4.61,4.95,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,26396,1450299137475327273,20250625031918,170416107,19.490670,-99.174150,Azcapotzalco,NaN,Entire condo,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,4.00
26397,26397,1450300528106131951,20250625031918,358250534,19.391438,-99.181881,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26399,26399,1450394952972090126,20250625031918,24161895,19.441713,-99.161810,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26400,26400,1450438287340754798,20250625031918,703177347,19.427570,-99.175410,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
f6=f_result.to_csv("f6.csv", index=False)

In [75]:
df6 = df.groupby(['host_is_superhost'])['host_is_superhost'].count()
df6

host_is_superhost
f    15365
t     9677
Name: host_is_superhost, dtype: int64

In [76]:
# g) Filtro por superhost
g_result = df[df["host_is_superhost"] == "t"]   # o True si ya está como boolean
g_result

,Unnamed: 0,id,scrape_id,host_id,latitude,longitude,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,...,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,reviews_per_month,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location
4,4,70644,20250625031918,212109,19.354480,-99.162170,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,132,8,0,9,0.81,4.92,4.91,4.96,4.98,4.96
6,6,165772,20250625031918,790208,19.408260,-99.186590,Miguel Hidalgo,NaN,Entire home,Entire home/apt,...,383,31,0,38,2.26,4.88,4.91,4.83,4.88,4.75
7,7,171109,20250625031918,816295,19.396750,-99.175810,Benito Juárez,NaN,Private room in rental unit,Private room,...,117,10,3,7,0.85,4.84,4.86,4.61,4.95,4.96
8,8,180808,20250625031918,36836,19.423900,-99.168900,Cuauhtémoc,NaN,Entire loft,Entire home/apt,...,60,9,0,5,0.37,4.82,4.90,4.77,4.90,4.90
9,9,187030,20250625031918,899360,19.410570,-99.177300,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,103,0,0,0,0.62,4.57,4.66,4.66,4.88,4.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26373,26373,1449312330909334226,20250625031918,569838375,19.372230,-99.164427,Benito Juárez,NaN,Entire rental unit,Entire home/apt,...,1,1,1,0,1.00,5.00,5.00,5.00,5.00,5.00
26374,26374,1449347506455590202,20250625031918,571653984,19.441612,-99.195800,Miguel Hidalgo,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26376,26376,1449724386306602095,20250625031918,151816281,19.457048,-99.214448,Miguel Hidalgo,NaN,Private room in rental unit,Private room,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26393,26393,1450244485815740442,20250625031918,431645813,19.350020,-99.164490,Coyoacán,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26398,26398,1450345027980478127,20250625031918,594251711,19.419767,-99.175294,Cuauhtémoc,NaN,Entire rental unit,Entire home/apt,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
f7=g_result.to_csv("f7.csv", index=False)

In [78]:
# h) Columnas en posiciones impares (1, 3, 5…)
#MÉTODO 1
odd_cols = [col for i, col in enumerate(df.columns, start=0) if i % 2 == 1]
h_result = df[odd_cols]
h_result.head()

,id,host_id,longitude,neighbourhood_group_cleansed,room_type,host_location,host_response_rate,host_is_superhost,host_total_listings_count,host_identity_verified,...,minimum_maximum_nights,minimum_nights_avg_ntm,has_availability,availability_60,availability_365,number_of_reviews,number_of_reviews_l30d,reviews_per_month,review_scores_accuracy,review_scores_communication
0,35797,153786,-99.27178,NaN,Entire home/apt,"Mexico City, Mexico",NaN,f,1.0,t,...,7.0,1.0,t,59,364,0,0,NaN,NaN,NaN
1,44616,196253,-99.17794,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,13.0,t,...,180.0,1.0,t,59,360,65,0,0.39,4.56,4.78
2,56074,265650,-99.15605,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,5.0,t,...,250.0,15.0,t,33,338,84,0,0.48,4.95,4.94
3,67703,334451,-99.16857,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,4.0,t,...,30.0,2.0,t,4,267,50,0,0.30,4.82,4.92
4,70644,212109,-99.16217,NaN,Entire home/apt,"Mexico City, Mexico",100%,t,4.0,t,...,180.0,3.4,t,25,211,132,0,0.81,4.91,4.98

In [79]:
#Columnas incrementales en un fator
#MÉTODO 2
columnas= df.iloc[:, 1::2] #Columnas con incrementos de 2 a partir de la columna 1
columnas

,id,host_id,longitude,neighbourhood_group_cleansed,room_type,host_location,host_response_rate,host_is_superhost,host_total_listings_count,host_identity_verified,...,minimum_maximum_nights,minimum_nights_avg_ntm,has_availability,availability_60,availability_365,number_of_reviews,number_of_reviews_l30d,reviews_per_month,review_scores_accuracy,review_scores_communication
0,35797,153786,-99.271780,NaN,Entire home/apt,"Mexico City, Mexico",NaN,f,1.0,t,...,7.0,1.0,t,59,364,0,0,NaN,NaN,NaN
1,44616,196253,-99.177940,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,13.0,t,...,180.0,1.0,t,59,360,65,0,0.39,4.56,4.78
2,56074,265650,-99.156050,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,5.0,t,...,250.0,15.0,t,33,338,84,0,0.48,4.95,4.94
3,67703,334451,-99.168570,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,4.0,t,...,30.0,2.0,t,4,267,50,0,0.30,4.82,4.92
4,70644,212109,-99.162170,NaN,Entire home/apt,"Mexico City, Mexico",100%,t,4.0,t,...,180.0,3.4,t,25,211,132,0,0.81,4.91,4.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1450299137475327273,170416107,-99.174150,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,3.0,t,...,365.0,1.2,t,57,359,1,1,1.00,5.00,5.00
26397,1450300528106131951,358250534,-99.181881,NaN,Entire home/apt,"Mexico City, Mexico",100%,NaN,27.0,t,...,365.0,1.0,t,59,364,0,0,NaN,NaN,NaN
26398,1450345027980478127,594251711,-99.175294,NaN,Entire home/apt,"Mexico City, Mexico",100%,t,6.0,t,...,365.0,1.0,t,59,364,0,0,NaN,NaN,NaN
26399,1450394952972090126,24161895,-99.161810,NaN,Entire home/apt,"Mexico City, Mexico",100%,f,1.0,t,...,1125.0,2.0,t,36,341,0,0,NaN,NaN,NaN
26400,1450438287340754798,703177347,-99.175410,NaN,Entire home/apt,"Mexico City, Mexico",NaN,f,1.0,t,...,120.0,3.0,t,60,270,0,0,NaN,NaN,NaN

In [80]:
f8=columnas.to_csv("f8.csv", index=False)